import type { HubTemplateDef } from "./topic-copy";

/** 중복 제거된 1차 양식 목록 */
export const HUB_TEMPLATE_CATALOG: HubTemplateDef[] = [
  {
    id: "goldendoodle-adoption",
    label: "골든두들분양 (지역 SEO 양식)",
    topicLabel: "골든두들분양",
    kind: "breed-dog",
    seoKeyword: "골든두들분양",
  },
  {
    id: "dog-adoption",
    label: "강아지분양 (지역 SEO 양식)",
    topicLabel: "강아지분양",
    kind: "dog-adoption",
    seoKeyword: "강아지분양",
    promptExtra: "특정 견종이 아니라 강아지 분양 전반의 기본 안내. 건강·계약·집 준비·안전한 진행.",
  },
  {
    id: "cat-adoption",
    label: "고양이분양 (지역 SEO 양식)",
    topicLabel: "고양이분양",
    kind: "cat-adoption",
    seoKeyword: "고양이분양",
    promptExtra: "특정 묘종이 아니라 고양이 분양 전반의 기본 안내. 건강·계약·집 준비·안전한 진행.",
  },
  {
    id: "dog-rehome",
    label: "강아지파양 (지역 SEO 양식)",
    topicLabel: "강아지파양",
    kind: "dog-rehome",
    seoKeyword: "강아지파양",
    promptExtra:
      "피치 못할 사정으로 더 이상 함께할 수 없을 때의 파양·무료분양 안내. 후원·봉사·기부·안락사없는(안락사 프리) 홍보 문구는 절대 넣지 말 것.",
  },
  {
    id: "cat-rehome",
    label: "고양이파양 (지역 SEO 양식)",
    topicLabel: "고양이파양",
    kind: "cat-rehome",
    seoKeyword: "고양이파양",
    promptExtra:
      "피치 못할 사정으로 더 이상 함께할 수 없을 때의 파양·무료분양 안내. 후원·봉사·기부·안락사없는(안락사 프리) 홍보 문구는 절대 넣지 말 것.",
  },
  {
    id: "dog-shelter",
    label: "강아지보호소 (지역 SEO 양식)",
    topicLabel: "강아지보호소",
    kind: "dog-shelter",
    seoKeyword: "강아지보호소",
    promptExtra:
      "보호소·유기견 보호 시설 안내이되, 후원·봉사·기부·안락사없는 홍보는 금지. 피치 못할 사정의 파양 연계·무료분양·입양 절차·건강 확인 중심으로.",
  },
  {
    id: "stray-dog-shelter",
    label: "유기견보호소 (지역 SEO 양식)",
    topicLabel: "유기견보호소",
    kind: "dog-shelter",
    seoKeyword: "유기견보호소",
    promptExtra:
      "유기견 보호소 안내. 후원·봉사·기부·안락사없는 홍보 금지. 입양·무료분양·건강 확인·피치 못할 사정 파양 연계 중심.",
  },
  {
    id: "vet-clinic",
    label: "동물병원 (지역 SEO 양식)",
    topicLabel: "동물병원",
    kind: "vet",
    seoKeyword: "동물병원",
    promptExtra: "동물병원 선택 가이드. 응급진료·24시 동물병원 내용을 자연스럽게 포함. 과장 치료 효과 단정 금지.",
  },
  {
    id: "vet-marketing",
    label: "동물병원마케팅 (지역 SEO 양식)",
    topicLabel: "동물병원마케팅",
    kind: "vet-marketing",
    seoKeyword: "동물병원마케팅",
    promptExtra: "동물병원 마케팅·홍보·신규 환자 유입 관점의 B2B/운영자 안내. 허위 광고·의료법 위반 소지 문구 금지.",
  },
  {
    id: "demolition",
    label: "철거업체 (지역 SEO 양식)",
    topicLabel: "철거업체",
    kind: "service",
    seoKeyword: "철거업체",
    promptExtra: "건물·인테리어 철거 업체 선택 가이드. 견적·허가·폐기물·일정·안전.",
  },
  {
    id: "white-terrier-adoption",
    label: "화이트테리어분양 (지역 SEO 양식)",
    topicLabel: "화이트테리어분양",
    kind: "breed-dog",
    seoKeyword: "화이트테리어분양",
  },
  {
    id: "bernedoodle-adoption",
    label: "버니두들분양 (지역 SEO 양식)",
    topicLabel: "버니두들분양",
    kind: "breed-dog",
    seoKeyword: "버니두들분양",
    promptExtra: "버니즈 마운틴독×푸들 믹스(Bernedoodle).",
  },
  {
    id: "golden-retriever-adoption",
    label: "골든리트리버분양 (지역 SEO 양식)",
    topicLabel: "골든리트리버분양",
    kind: "breed-dog",
    seoKeyword: "골든리트리버분양",
  },
  {
    id: "shetland-sheepdog-adoption",
    label: "셔틀랜드쉽독분양 (지역 SEO 양식)",
    topicLabel: "셔틀랜드쉽독분양",
    kind: "breed-dog",
    seoKeyword: "셔틀랜드쉽독분양",
  },
  {
    id: "dachshund-adoption",
    label: "닥스훈트분양 (지역 SEO 양식)",
    topicLabel: "닥스훈트분양",
    kind: "breed-dog",
    seoKeyword: "닥스훈트분양",
  },
  {
    id: "pomsky-adoption",
    label: "폼스키분양 (지역 SEO 양식)",
    topicLabel: "폼스키분양",
    kind: "breed-dog",
    seoKeyword: "폼스키분양",
    promptExtra: "포메라니안×허스키 믹스(Pomsky).",
  },
  {
    id: "coton-de-tulear-adoption",
    label: "꼬똥드툴레아분양 (지역 SEO 양식)",
    topicLabel: "꼬똥드툴레아분양",
    kind: "breed-dog",
    seoKeyword: "꼬똥드툴레아분양",
  },
  {
    id: "coton-bichon-mix-adoption",
    label: "꼬숑분양 (지역 SEO 양식)",
    topicLabel: "꼬숑분양",
    kind: "breed-dog",
    seoKeyword: "꼬숑분양",
    promptExtra: "꼬똥드툴레아+비숑 믹스(꼬숑). 품종 설명을 설득력 있게.",
  },
  {
    id: "maine-coon-adoption",
    label: "메인쿤분양 (지역 SEO 양식)",
    topicLabel: "메인쿤분양",
    kind: "breed-cat",
    seoKeyword: "메인쿤분양",
  },
  {
    id: "neva-masquerade-adoption",
    label: "네바마스커레이드분양 (지역 SEO 양식)",
    topicLabel: "네바마스커레이드분양",
    kind: "breed-cat",
    seoKeyword: "네바마스커레이드분양",
  },
  {
    id: "pomeranian-adoption",
    label: "포메라니안분양 (지역 SEO 양식)",
    topicLabel: "포메라니안분양",
    kind: "breed-dog",
    seoKeyword: "포메라니안분양",
  },
  {
    id: "russian-blue-adoption",
    label: "러시안블루분양 (지역 SEO 양식)",
    topicLabel: "러시안블루분양",
    kind: "breed-cat",
    seoKeyword: "러시안블루분양",
  },
  {
    id: "british-shorthair-adoption",
    label: "브리티쉬숏헤어분양 (지역 SEO 양식)",
    topicLabel: "브리티쉬숏헤어분양",
    kind: "breed-cat",
    seoKeyword: "브리티쉬숏헤어분양",
  },
  {
    id: "munchkin-adoption",
    label: "먼치킨분양 (지역 SEO 양식)",
    topicLabel: "먼치킨분양",
    kind: "breed-cat",
    seoKeyword: "먼치킨분양",
  },
  {
    id: "american-shorthair-adoption",
    label: "아메리칸숏헤어분양 (지역 SEO 양식)",
    topicLabel: "아메리칸숏헤어분양",
    kind: "breed-cat",
    seoKeyword: "아메리칸숏헤어분양",
  },
  {
    id: "sphynx-adoption",
    label: "스핑크스분양 (지역 SEO 양식)",
    topicLabel: "스핑크스분양",
    kind: "breed-cat",
    seoKeyword: "스핑크스분양",
  },
  {
    id: "abyssinian-adoption",
    label: "아비시니안분양 (지역 SEO 양식)",
    topicLabel: "아비시니안분양",
    kind: "breed-cat",
    seoKeyword: "아비시니안분양",
  },
  {
    id: "schnauzer-adoption",
    label: "슈나우저분양 (지역 SEO 양식)",
    topicLabel: "슈나우저분양",
    kind: "breed-dog",
    seoKeyword: "슈나우저분양",
  },
  {
    id: "maltipoo-adoption",
    label: "말티푸분양 (지역 SEO 양식)",
    topicLabel: "말티푸분양",
    kind: "breed-dog",
    seoKeyword: "말티푸분양",
    promptExtra: "말티즈×푸들 믹스(Maltipoo).",
  },
  {
    id: "bichon-frise-adoption",
    label: "비숑프리제분양 (지역 SEO 양식)",
    topicLabel: "비숑프리제분양",
    kind: "breed-dog",
    seoKeyword: "비숑프리제분양",
  },
  {
    id: "maltese-adoption",
    label: "말티즈분양 (지역 SEO 양식)",
    topicLabel: "말티즈분양",
    kind: "breed-dog",
    seoKeyword: "말티즈분양",
  },
  {
    id: "shih-tzu-adoption",
    label: "시츄분양 (지역 SEO 양식)",
    topicLabel: "시츄분양",
    kind: "breed-dog",
    seoKeyword: "시츄분양",
  },
  {
    id: "yorkshire-terrier-adoption",
    label: "요크셔테리어분양 (지역 SEO 양식)",
    topicLabel: "요크셔테리어분양",
    kind: "breed-dog",
    seoKeyword: "요크셔테리어분양",
  },
  {
    id: "toy-poodle-adoption",
    label: "토이푸들분양 (지역 SEO 양식)",
    topicLabel: "토이푸들분양",
    kind: "breed-dog",
    seoKeyword: "토이푸들분양",
  },
  {
    id: "scalp-tattoo",
    label: "두피문신 (지역 SEO 양식)",
    topicLabel: "두피문신",
    kind: "service",
    seoKeyword: "두피문신",
    promptExtra: "두피 문신(SMP 등) 시술 선택·주의·상담 가이드. 의료 효과 단정·과장 금지.",
  },
  {
    id: "nail-art",
    label: "네일아트 (지역 SEO 양식)",
    topicLabel: "네일아트",
    kind: "service",
    seoKeyword: "네일아트",
    promptExtra: "네일아트 샵·시술 선택 가이드. 위생·디자인·유지 관리.",
  },
  {
    id: "rooftop-landscape-interior",
    label: "옥상조경인테리어 (지역 SEO 양식)",
    topicLabel: "옥상조경인테리어",
    kind: "service",
    seoKeyword: "옥상조경인테리어",
    promptExtra: "옥상·테라스 조경 및 인테리어 업체 안내. 방수·하중·식물·시공 순서.",
  },
  {
    id: "jeju-real-estate-ad",
    label: "제주도부동산광고 (지역 SEO 양식)",
    topicLabel: "제주도부동산광고",
    kind: "service",
    seoKeyword: "제주도부동산광고",
    promptExtra: "제주도 위주 부동산 광고·매물 홍보. 투자 수익 단정·허위 시세 금지. 제주 지역 특성 반영.",
  },
  {
    id: "dog-grooming-academy",
    label: "애견미용학원 (지역 SEO 양식)",
    topicLabel: "애견미용학원",
    kind: "service",
    seoKeyword: "애견미용학원",
    promptExtra: "애견미용 학원·자격·커리큘럼 선택 가이드.",
  },
  {
    id: "dog-kindergarten",
    label: "애견유치원 (지역 SEO 양식)",
    topicLabel: "애견유치원",
    kind: "service",
    seoKeyword: "애견유치원",
    promptExtra: "애견유치원·데이케어 선택 가이드. 안전·사회화·원장 소통.",
  },
  {
    id: "dog-cafe",
    label: "애견카페 (지역 SEO 양식)",
    topicLabel: "애견카페",
    kind: "service",
    seoKeyword: "애견카페",
    promptExtra: "애견카페 이용·선택 가이드. 위생·동반 예절·공간.",
  },
  {
    id: "cocker-spaniel-adoption",
    label: "코카스파니엘분양 (지역 SEO 양식)",
    topicLabel: "코카스파니엘분양",
    kind: "breed-dog",
    seoKeyword: "코카스파니엘분양",
  },
  {
    id: "bengal-cat-adoption",
    label: "뱅갈고양이분양 (지역 SEO 양식)",
    topicLabel: "뱅갈고양이분양",
    kind: "breed-cat",
    seoKeyword: "뱅갈고양이분양",
  },
  {
    id: "boston-terrier-adoption",
    label: "보스턴테리어분양 (지역 SEO 양식)",
    topicLabel: "보스턴테리어분양",
    kind: "breed-dog",
    seoKeyword: "보스턴테리어분양",
  },
  {
    id: "bernese-mountain-dog-adoption",
    label: "버니즈마운틴독분양 (지역 SEO 양식)",
    topicLabel: "버니즈마운틴독분양",
    kind: "breed-dog",
    seoKeyword: "버니즈마운틴독분양",
  },
  {
    id: "chow-chow-adoption",
    label: "차우차우분양 (지역 SEO 양식)",
    topicLabel: "차우차우분양",
    kind: "breed-dog",
    seoKeyword: "차우차우분양",
  },
  {
    id: "chihuahua-adoption",
    label: "치와와분양 (지역 SEO 양식)",
    topicLabel: "치와와분양",
    kind: "breed-dog",
    seoKeyword: "치와와분양",
  },
  {
    id: "dalmatian-adoption",
    label: "달마시안분양 (지역 SEO 양식)",
    topicLabel: "달마시안분양",
    kind: "breed-dog",
    seoKeyword: "달마시안분양",
  },
  {
    id: "doberman-adoption",
    label: "도베르만분양 (지역 SEO 양식)",
    topicLabel: "도베르만분양",
    kind: "breed-dog",
    seoKeyword: "도베르만분양",
  },
  {
    id: "english-bulldog-adoption",
    label: "잉글리쉬불독분양 (지역 SEO 양식)",
    topicLabel: "잉글리쉬불독분양",
    kind: "breed-dog",
    seoKeyword: "잉글리쉬불독분양",
  },
  {
    id: "french-bulldog-adoption",
    label: "프렌치불독분양 (지역 SEO 양식)",
    topicLabel: "프렌치불독분양",
    kind: "breed-dog",
    seoKeyword: "프렌치불독분양",
  },
  {
    id: "italian-greyhound-adoption",
    label: "이탈리안그레이하운드분양 (지역 SEO 양식)",
    topicLabel: "이탈리안그레이하운드분양",
    kind: "breed-dog",
    seoKeyword: "이탈리안그레이하운드분양",
  },
  {
    id: "alaskan-malamute-adoption",
    label: "알래스칸말라뮤트분양 (지역 SEO 양식)",
    topicLabel: "알래스칸말라뮤트분양",
    kind: "breed-dog",
    seoKeyword: "알래스칸말라뮤트분양",
  },
  {
    id: "miniature-pinscher-adoption",
    label: "미니핀분양 (지역 SEO 양식)",
    topicLabel: "미니핀분양",
    kind: "breed-dog",
    seoKeyword: "미니핀분양",
    promptExtra: "미니어처 핀셔(미니핀).",
  },
  {
    id: "norwegian-forest-cat-adoption",
    label: "노르웨이숲고양이분양 (지역 SEO 양식)",
    topicLabel: "노르웨이숲고양이분양",
    kind: "breed-cat",
    seoKeyword: "노르웨이숲고양이분양",
  },
  {
    id: "old-english-sheepdog-adoption",
    label: "올드잉글리쉬쉽독분양 (지역 SEO 양식)",
    topicLabel: "올드잉글리쉬쉽독분양",
    kind: "breed-dog",
    seoKeyword: "올드잉글리쉬쉽독분양",
  },
  {
    id: "pekingese-adoption",
    label: "페키니즈분양 (지역 SEO 양식)",
    topicLabel: "페키니즈분양",
    kind: "breed-dog",
    seoKeyword: "페키니즈분양",
  },
  {
    id: "persian-cat-adoption",
    label: "페르시안고양이분양 (지역 SEO 양식)",
    topicLabel: "페르시안고양이분양",
    kind: "breed-cat",
    seoKeyword: "페르시안고양이분양",
  },
  {
    id: "labrador-retriever-adoption",
    label: "래브라도리트리버분양 (지역 SEO 양식)",
    topicLabel: "래브라도리트리버분양",
    kind: "breed-dog",
    seoKeyword: "래브라도리트리버분양",
  },
  {
    id: "ragdoll-adoption",
    label: "랙돌분양 (지역 SEO 양식)",
    topicLabel: "랙돌분양",
    kind: "breed-cat",
    seoKeyword: "랙돌분양",
  },
  {
    id: "scottish-fold-adoption",
    label: "스코티쉬폴드분양 (지역 SEO 양식)",
    topicLabel: "스코티쉬폴드분양",
    kind: "breed-cat",
    seoKeyword: "스코티쉬폴드분양",
  },
  {
    id: "shiba-inu-adoption",
    label: "시바이누분양 (지역 SEO 양식)",
    topicLabel: "시바이누분양",
    kind: "breed-dog",
    seoKeyword: "시바이누분양",
    promptExtra: "시바이누(시바견). SEO에 시바견·시바이누 모두 자연스럽게.",
  },
  {
    id: "standard-poodle-adoption",
    label: "스탠다드푸들분양 (지역 SEO 양식)",
    topicLabel: "스탠다드푸들분양",
    kind: "breed-dog",
    seoKeyword: "스탠다드푸들분양",
  },
  {
    id: "papillon-adoption",
    label: "빠삐용분양 (지역 SEO 양식)",
    topicLabel: "빠삐용분양",
    kind: "breed-dog",
    seoKeyword: "빠삐용분양",
    promptExtra: "빠삐용(파피용, Papillon). SEO에 파피용도 자연스럽게.",
  },
  {
    id: "welsh-corgi-adoption",
    label: "웰시코기분양 (지역 SEO 양식)",
    topicLabel: "웰시코기분양",
    kind: "breed-dog",
    seoKeyword: "웰시코기분양",
  },
  {
    id: "border-collie-adoption",
    label: "보더콜리분양 (지역 SEO 양식)",
    topicLabel: "보더콜리분양",
    kind: "breed-dog",
    seoKeyword: "보더콜리분양",
  },
];

export function getHubTemplateDef(id?: string | null) {
  const key = String(id || "").trim();
  if (!key) return HUB_TEMPLATE_CATALOG[0] || null;
  return HUB_TEMPLATE_CATALOG.find((row) => row.id === key) || null;
}
